---
title: "Multivariate Statistics"
author: "Shadab Alam"
date: "12/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Two sample T-Test For diference in means
#Input the summary statistics
xbar1=1.5714
xbar2=1.5361
s1=1.3126
s2=1.3251
n1=2529
n2=804
dfs=min(n1-1,n2-1)
tdata=(xbar1-xbar2)/sqrt((s1^2/n1)+(s2^2/n2))
pvalue=2*pt(tdata,df=dfs,lower.tail = FALSE)
pvalue;tdata#Test statistic and p_value

```

```{r}
#Two sample Z Test for Difference in proportions
#Input the summary statistics
#some of these will override the values
x1=707
x2=215
n1=2529
n2=804
p1=x1/n1
p2=x2/n2
ppooled=(x1+x2)/(n1+n2)
zdata=(p1-p2)/sqrt(ppooled*(1-ppooled)*((1/n1)+(1/n2)))
pvalue=2*pnorm(zdata,lower.tail=FALSE)
zdata;pvalue #Test statistic and p-value

```

```{r}
#Chi Square Test for Homogenity of Proportions
#Create a Table
table1=as.table(rbind(c(410,340,250),c(95,85,70)))
dimnames(table1)=list(Data.Set=c("Training Set","Test Set"),Status=c("Married","Single","Other"))
Xsq_data=chisq.test(table1)
Xsq_data$statistic #Test Statistic
Xsq_data$p.value #P-value
Xsq_data$expected #Expected counts
```

```{r}
#Chi-Square Goodness of Fit of Multimonial Data
#Population proportions
p_status=c(0.40,0.35,0.25)
# Observed frequencies 
o_status=c(36,35,29)
chisq.test(o_status,p=p_status)
```

```{r}
# Anova
a=c(30,40,50,60);b=c(25,30,50,55)
c=c(25,30,40,45)
ab=append(a,b)
datavalues=append(ab,c)
datalabels=factor(c(rep("a",length(a)),rep("b",length(b)),rep("c",length(c))))
anova.results=aov(datavalues~datalabels)

```




