---
title: "Multiple Regression and Model Building"
author: "Shadab Alam"
date: "1/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Input and prepare Cereals data
cereal=read.csv("C:/Users/shada/Downloads/DMPA_data_sets/Data sets/cereals.csv",stringsAsFactors = TRUE,header = TRUE)
which(is.na(cereal$Sugars))
#Record 58 is missing from sugar variable data
cereal[-58,]
dat=data.frame(Rating=cereal$Rating,Sugars=cereal$Sugars,Fibre=cereal$Fiber)
head(dat)
```

```{r}
# Three variable scaterplot 
#pairs(~dat$Rating+dat$Sugars+dat$Fibre) #scatterplot using pairs function
library(scatterplot3d)
#Colors By Rating
rg=colorRampPalette(c("red","green"))(76)
sp=scatterplot3d(dat[1:76,1:3],pch=16,color="red")
library(rgl)
plot3d(dat[1:76,1:3],type="s",col=as.integer(cereal$Shelf))

```

```{r}
#Individual variable scatter plots of Rating vs Sugars and Fiber
par(mfrow=c(1,2))
lm91=lm(Rating~Sugars,data = cereal)
lm91
anova(lm91)
lm92=lm(Rating~Fiber,data=cereal)
lm92
plot(Rating~Sugars,data=cereal,pch=16,col="red",xlab="Sugar",ylab="Rating")
abline(lm91,col="green")
plot(Rating~Fiber,data=cereal,pch=16,col="red",xlab="Fibre",ylab="Rating")
abline(lm92,col="green") #abline takes the argument intercept and slope from the linear regression model result and draws a straight based on the intercept and slope .
#Reset plot area
par(mfrow=c(1,1))

```

```{r}
# Multiple Regression :<Insert Carriage return.>#Output,t-test,F-Tests
mreg1=lm(Rating~Sugars+Fiber,data=cereal)
summary(mreg1)
#t=tests are in the
#Coefficients table
#F-test:bottom row
#of the output
ma1=anova(mreg1)
ma1
#SSR is broken up
#between predictors
```

```{r}
#Confidence Intervals
# CI for Beta coefficients 
confint(mreg1,level=0.95)
predict(mreg1,newdata=data.frame(Sugars=5,Fiber=5),interval =c("confidence"))
#Prediction Interval
predict(mreg1,newdata=data.frame(Sugars=5,Fiber=5),interval=c("prediction"))

```

```{r}
#Dot plot of Rating by Shelf
#Create indicator variables
cereal$Shelf1=ifelse(cereal$Shelf==1,1,0)
cereal$Shelf2=ifelse(cereal$Shelf==2,1,0)
stripchart(Rating~Shelf,data=cereal,method="stack",pch=0,col=c("green","blue","red"),main="Rating by shelf",offset=0.5,ylab="Shelf")
```

```{r}
# Regression including Shelf effect
#All shelves
mreg2=lm(Rating~Shelf1+Shelf2,data=cereal)
summary(mreg2)
anova(mreg2)
#One Shelf 
mreg3=lm(Rating~Sugars+Fiber+Shelf1+Shelf2,data=cereal)
summary(mreg3)
anova(mreg3)

```

```{r}
#3D scatterplot with groups
library(scatterplot3d)
sp=scatterplot3d(z=sort(cereal$Rating),y=cereal$Sugars,x=cereal$Fiber,pch=16,xlab="Fiber",ylab="Sugars",zlab="Rating",main="3D Scatterplot")
library(rgl)
plot3d(z=sort(cereal$Rating),y=cereal$Sugars,x=cereal$Fiber,pch=16,type="s",col=as.integer(cereal$Shelf))
```


```{r}
#Sequential Sum Of Square
mreg4.1=lm(Rating~Sugars+Fiber+Shelf1+Shelf2,data=cereal)
anova(mreg4.1)
mreg4.2=lm(Rating~Shelf1+Shelf2+Sugars+Fiber,data = cereal)
anova(mreg4.2)
```

```{r}
# Multicollinearity to check the correlation among the predictor variables
datam=matrix(c(cereal$Fiber,cereal$Sugars,cereal$Shelf2),ncol = 3)
colnames(datam)=c("Fibre","Sugars","Shelf2")
cor(datam)
pairs(~Sugars+Fiber+Potass,data=cereal)
#VIFs
mreg5=lm(Rating~Sugars+Fiber+Shelf2+Potass,data=cereal)
library(car)
vif(mreg5)
```

```{r}
#Gas mileage data example
#Read in Gas data
gas=read.csv("C:/Users/shada/Downloads/DMPA_data_sets/Data sets/gas_mileage.txt",stringsAsFactors = TRUE,header = TRUE)
head(gas)
gas$lnmpg=log(gas$MPG)
```


