---
title: "Neural Network"
author: "Shadab Alam"
date: "2/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
adult=read.csv("C:/Users/shada/Desktop/DMPA_data_sets/Data sets/adult/Clem3Training",stringsAsFactors = TRUE)
head(adult)

```

```{r}
# collapse some of the categories by giving them the same factor label
levels(adult$marital.status)
levels(adult$workclass)
levels(adult$marital.status)[2:4]="Married"
levels(adult$workclass)[c(2,3,8)]="Gov"
levels(adult$workclass)[c(5,6)]="Self"
levels(adult$marital.status)
levels(adult$workclass)

# We will work with a small sample of data
adult=adult[1:500,]

```

```{r}
# Determine how many indicator variable are needed
unique(adult$income) #One variable for income
unique(adult$sex)    # One variable for sex
unique(adult$race)   # Four variable for race
unique(adult$workclass) # Three variables for work class
unique(adult$marital.status) # Four variables for marital status

```

```{r}
# Create indicator variables
adult$race_white=adult$race_black=adult$race_as.pac.is=adult$race_am.in.esk=adult$we_gov=adult$we_self=adult$we_priv=adult$ms_marr=adult$ms_div=adult$ms_sep=adult$ms_wid=adult$income_g50k=adult$sex2=c(rep(0,length(adult$income)))

for(i in 1:length(adult$income)){
  if(adult$income[i]==">50k.")
    adult$income_g50k[i]=1
  if(adult$sex[i]=="Male")
    adult$sex2[i]=1
  if(adult$race[i]=="White")
    adult$race_white[i]=1
  if(adult$race[i]=="Amer-Indian-Eskimo")
    adult$race_am.in.esk[i]=1
  if(adult$race[i]=="Asian-Pac-Islander")
    adult$race_as.pac.is[i]=1
  if(adult$race[i]=="Black")
    adult$race_black[i]=1
  if(adult$workclass[i]=="Gov")
    adult$we_gov[i]=1
  if(adult$workclass[i]=="Self")
    adult$we_self[i]=1
  if(adult$workclass[i]=="Private")
    adult$we_priv[i]=1
  if(adult$marital.status[i]=="Married")
    adult$ms_marr[i]=1
  if(adult$marital.status[i]=="Divorced")
    adult$ms_div[i]=1
  if(adult$marital.status[i]=="Separated")
    adult$ms_sep[i]=1
  if(adult$marital.status[i]=="Widowed")
    adult$ms_wid[i]=1
}
```

```{r}
# Minimax transform the continuous variables
adult$age_mm=(adult$age-min(adult$age))/(max(adult$age)-min(adult$age))
adult$edu.num_mm=(adult$education.num-min(adult$education.num))/(max(adult$education.num)-min(adult$education.num))
adult$capital.gain_mm=(adult$capital.gain-min(adult$capital.gain))/(max(adult$capital.gain)-min(adult$capital.gain))
adult$capital.loss_mm=(adult$capital.loss-min(adult$capital.loss))/(max(adult$capital.loss)-min(adult$capital.loss))
adult$hours.p.w_mm=(adult$hours.per.week-min(adult$hours.per.week))/(max(adult$hours.per.week)-min(adult$hours.per.week))
newdat=as.data.frame(adult[,-c(1:15)]) 
# note:- Here only 9 variables are taken using sensitivity analysis in order of their importance for classification,and 6 variables have been excluded i.e. "demoweight", "education", "occupation", "relationship", "native.country", "income".
```

```{r}
#Run the neural net 
library(nnet) # Requires package nnet 
net.dat=nnet(income_g50k~.,data=newdat,size=8)
table(round(net.dat$fitted.values,1)) # if fitted values are all the same,rerun nnet
net.dat$wts # Weights
hist(net.dat$wts)3

```



