---
subtitle: "univariate Statistical Analysis"
author: "Shadab Alam"
date: "12/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Input The Chuurn Data Set
 churn=read.csv("C:/Users/shada/Downloads/DMPA_data_sets/Data sets/churn.txt",stringsAsFactors = TRUE)
#Using Head to find the first 6 records
head(churn)
```

```{r}
#Analyze a subgroup of data
subchurn=subset(churn,churn$Int.l.Plan=="yes" & churn$VMail.Plan=="yes" & churn$Day.Mins>220)
head(subchurn)
summary(subchurn$CustServ.Calls)
length(subchurn$CustServ.Calls)
```

```{r}
# One Sample T-Test and confidence interval for Mean 
mean.test=t.test(x=subchurn$CustServ.Calls,mu=2.4,conf.level = 0.95)
mean.test$statistic
mean.test$p.value
mean.test$conf.int
```

```{r}
# One Sample proportion Test And Confidence Interval
Churn_Tab=table(churn$Churn.)
num.churn=Churn_Tab[2] #Churners
sample.size=dim(churn)[1] #Sample size
p=num.churn/sample.size #Point Estimate
z_data=(p-0.15)/sqrt((0.15*(1-0.15))/sample.size)
error=qnorm(.975,mean=0,sd=1)*sqrt((p*(1-p))/sample.size)
lower.bound=p-error
upper.bound=p+error
p.value=2*pnorm(z_data,mean=0,sd=1)
z_data;p.value #Test Statistic,p-value
lower.bound;upper.bound #Confidence interval#


```


